routes/todo.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    jsonify,
)
from models.todo import Todo
from routes import (
    current_user,
    login_required,
)
from utils import (
    log,
)
import json


main = Blueprint('todo', __name__)


@main.route("/", methods=['GET'])
@login_required
def index():
    return render_template("todo/index.html")


@main.route("/todos", methods=['GET'])
def todos():
    u = current_user()
    ts = Todo.find_all(user_id=u.id)
    return jsonify([t.json() for t in ts])


@main.route("/add", methods=['POST'])
def add():
    form = json.loads(request.data.decode('utf-8'))
    t = Todo.new(form)
    u = current_user()
    t.user_id = u.id
    t.save()
    log(t.json())
    return jsonify(t.json())


@main.route("/delete/<string:id>/")
def delete(id):
    Todo.delete(id)
    return json.dumps({'success': True}), 200, {
        'ContentType': 'application/json'}


@main.route("/update", methods=['POST'])
def update():
    form = json.loads(request.data.decode('utf-8'))
    tid = form['id']
    t = Todo.update(tid, form)
    return jsonify(t.json())

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)
from models.user import User
from utils import log


main = Blueprint('user', __name__)


@main.route("/add", methods=['POST'])
def add():
    form = request.form
    u = User.register(form)
    if u is None:
        session['message'] = "Register Failed"
    else:
        session['message'] = "Register Done"
    return redirect(url_for('welcome.welcome'))

routes/welcome.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)
from models.user import User
from routes import (
    login_required,
    current_user,
)
from utils import log


main = Blueprint('welcome', __name__)


@main.route("/", methods=['GET'])
def welcome():
    u = current_user()
    if u is None:
        username = "Stranger"
    else:
        return redirect(url_for(".index"))
    template = render_template(
        "welcome.html", username=username, message=session.get('message', ''))
    r = make_response(template)
    r.set_cookie('cookie_name', 'RUA')
    return r


@main.route("/login", methods=['POST'])
def login():
    u = User.validate_login(request.form)
    if u is None:
        return render_template("welcome.html", username="Stranger", message="User Not Exist")
    else:
        session["uid"] = u.id
        return redirect(url_for(".index"))


@main.route("/index")
@login_required
def index():
    u = current_user()
    return render_template("index.html", username=u.username)


@main.route("/logout", methods=['POST'])
def logout():
    session.pop("uid")
    return redirect(url_for(".welcome"))

templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Index</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>

<body>
    <h1>Hello，{{ username }}</h1>
    <br>
    <form action={{ url_for( ".logout") }} method="post">
        <button type="submit">Sign Out</button>
    </form>
    <a href={{ url_for( "todo.index") }}>Todo</a>
    <a href="">Weibo</a>
    <a href="">Blog</a>
</body>

</html>

templates/welcome.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Welcome</title>
    <!-- <link rel="stylesheet" href="/static/css/demo.css"> -->
    <link rel="stylesheet" href="/static/css/demo.css">
</head>

<body>
    <video autoplay loop id="id-video-ddf">
        <source src="static/mv/Bad_Apple.mp4" type="video/mp4">
    </video>
    <section class="container">
        <div id="card">
            <figure class="front">
                <div class="imgcontainer">
                    <img src="/static/jpg/ddf.jpg" alt="Avatar" class="avatar">
                </div>
                <div class="login-form">
                    <h1>Hello, {{ username }}</h1>
                    <form action={{ url_for( ".login") }} method="post">
                        <label for="uname">
                            <b>Username</b>
                        </label>
                        <input type="text" name="username" placeholder="username">
                        <br>
                        <label for="psw">
                            <b>Password</b>
                        </label>
                        <input type="password" name="password" placeholder="password">
                        <br>
                        <button type="submit">Sign In</button>
                    </form>
                    <button id="id-button-front">Sign Up</button>
                    <h3>{{ message }}</h3>
                </div>
            </figure>
            <figure class="back">
                <div class="imgcontainer">
                    <img src="/static/jpg/ddf.jpg" alt="Avatar" class="avatar">
                </div>
                <div class="register-form">
                    <form action={{ url_for( "user.add") }} method="post">
                        <label for="uname">
                            <b>Username</b>
                        </label>
                        <input type="text" name="username" placeholder="username">
                        <br>
                        <label for="psw">
                            <b>Password</b>
                        </label>
                        <input type="password" name="password" placeholder="password">
                        <br>
                        <button type="submit">Sign Up</button>
                    </form>
                    <button id="id-button-back">Cancel</button>
                </div>
            </figure>
        </div>
    </section>
    <script src='/static/main.js'></script>
    <script src='/static/tool.js'></script>
</body>

</html>